//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LKS_Hotel_API_4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class fdCheckout
    {
        public int id { get; set; }
        public int reservationRoomId { get; set; }
        public int fdID { get; set; }
        public int qty { get; set; }
        public int totalPrice { get; set; }
        public int employeeId { get; set; }
    
        public virtual employee employee { get; set; }
        public virtual reservationRoom reservationRoom { get; set; }
        public virtual foodsAndDrink foodsAndDrink { get; set; }
    }
}
