//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LKS_Hotel_API_4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class reservationRoom
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public reservationRoom()
        {
            this.fdCheckouts = new HashSet<fdCheckout>();
            this.reservationCheckOuts = new HashSet<reservationCheckOut>();
            this.reservationRequestItems = new HashSet<reservationRequestItem>();
        }
    
        public int id { get; set; }
        public int reservationId { get; set; }
        public int roomId { get; set; }
        public System.DateTime startDateTime { get; set; }
        public int durationNights { get; set; }
        public int roomPrice { get; set; }
        public System.DateTime checkInDateTime { get; set; }
        public System.DateTime checkOutDateTime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<fdCheckout> fdCheckouts { get; set; }
        public virtual reservation reservation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<reservationCheckOut> reservationCheckOuts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<reservationRequestItem> reservationRequestItems { get; set; }
        public virtual Room Room { get; set; }
    }
}
